// examples/vue-remote/src/App.vue
<script setup>
import RemoteBadge from './RemoteBadge.vue';
</script>

<template>
  <main class="vue-remote-shell">
    <p class="eyebrow">Vue remote</p>
    <h1>Manifest-first Vue expose</h1>
    <RemoteBadge label="Previewed inside vue-remote" />
  </main>
</template>

<style>
body {
  margin: 0;
  background: #f3f8ee;
  color: #17220e;
  font-family: Avenir, Montserrat, sans-serif;
}

.vue-remote-shell {
  min-height: 100vh;
  padding: 4rem;
}

.eyebrow {
  color: #4a7c2c;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}
</style>

// examples/svelte-remote/src/App.svelte
<script>
  import RemotePanel from './RemotePanel.svelte';
</script>

<main class="svelte-remote-shell">
  <p class="eyebrow">Svelte remote</p>
  <h1>Manifest-first Svelte expose</h1>
  <RemotePanel title="Previewed inside svelte-remote" />
</main>

<style>
  :global(body) {
    margin: 0;
    background: #fff6ea;
    color: #2f1708;
    font-family: Charter, Georgia, serif;
  }

  .svelte-remote-shell {
    min-height: 100vh;
    padding: 4rem;
  }

  .eyebrow {
    color: #b1441b;
    font-family: Optima, Avenir, sans-serif;
    font-weight: 800;
    letter-spacing: 0.08em;
    text-transform: uppercase;
  }
</style>
